name: CI/CD Container

run-name: ${{ vicmukete }} building on ${{ github.ref }}

on:
  push:
  branches:
    - master


jobs:

  Image Build:

    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sample-image:latest .

      - name: Push to Dockerhub
        run: docker push ${{ vicmukete }}/sample-image:latest
