name: CI/CD Container-1

on: push


jobs:

  build:

    runs-on: ubuntu-latest
    steps:

        - uses: actions/checkout@v3

        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Image
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sample-image-pull:latest ./d2
          

        - name: Push to Dockerhub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/sample-image-pull:latest
